-- Adiciona campos para o layout SGAS
ALTER TABLE acoes
ADD COLUMN vagas INT NOT NULL DEFAULT 20,
ADD COLUMN categoria VARCHAR(100) NOT NULL DEFAULT 'Geral',
ADD COLUMN status VARCHAR(50) NOT NULL DEFAULT 'publicada',
ADD COLUMN cor VARCHAR(20) NOT NULL DEFAULT '#15803D';
